# Generated by Django 4.2.30 on 2026-09-25 16:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "solicitud_problema",
                    models.TextField(verbose_name="Actividad / solicitud / problema"),
                ),
                (
                    "accion",
                    models.CharField(max_length=255, verbose_name="Acción realizada"),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Contacto"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "ingreso_agenda_colectiva",
                    models.BooleanField(
                        default=False, verbose_name="¿Ingresa al tubo?"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("REGISTRADA", "Registrada"),
                            ("EN_REVISION", "En revisión"),
                            ("OBSERVADA", "Observada"),
                            ("VALIDADA", "Validada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="REGISTRADA",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "db_table": "actividad",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="AtencionSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_solicitante",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del solicitante"
                    ),
                ),
                (
                    "rut_solicitante",
                    models.CharField(max_length=12, verbose_name="RUT del solicitante"),
                ),
                (
                    "telefono_solicitante",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Teléfono del solicitante",
                    ),
                ),
                (
                    "requiere_visita",
                    models.BooleanField(
                        default=False, verbose_name="¿Requiere visita?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Atención social",
                "verbose_name_plural": "Atenciones sociales",
                "db_table": "atencion_social",
            },
        ),
        migrations.CreateModel(
            name="Compromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origen", models.CharField(max_length=150, verbose_name="Origen")),
                (
                    "solicitante",
                    models.CharField(max_length=200, verbose_name="Solicitante"),
                ),
                (
                    "territorio",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Territorio",
                    ),
                ),
                (
                    "area_apoyo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Área de apoyo",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(verbose_name="Descripción del requerimiento"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de registro",
                    ),
                ),
                (
                    "fecha_comprometida",
                    models.DateField(verbose_name="Fecha comprometida"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INGRESADO", "Ingresado"),
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("REALIZADO", "Realizado"),
                        ],
                        default="INGRESADO",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cierre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Compromiso",
                "verbose_name_plural": "Compromisos",
                "db_table": "compromiso",
                "ordering": ["fecha_comprometida"],
            },
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Versión"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="evidencias/",
                        verbose_name="Imagen (JPG/PNG, máx. 5 MB)",
                    ),
                ),
                (
                    "comentario",
                    models.TextField(blank=True, default="", verbose_name="Comentario"),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "estado_revision",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("OBSERVADA", "Observada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                        verbose_name="Estado de revisión",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia",
                "verbose_name_plural": "Evidencias",
                "db_table": "evidencia",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="GestionSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_gestion",
                    models.PositiveSmallIntegerField(
                        verbose_name="N° de gestión (1 a 3)"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VISITA", "Visita"),
                            ("INFORME", "Informe"),
                            ("BENEFICIO", "Beneficio"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("accion", models.CharField(max_length=255, verbose_name="Acción")),
                ("fecha", models.DateField(verbose_name="Fecha")),
            ],
            options={
                "verbose_name": "Gestión social",
                "verbose_name_plural": "Gestiones sociales",
                "db_table": "gestion_social",
                "ordering": ["numero_gestion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialCompromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INGRESADO", "Ingresado"),
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("REALIZADO", "Realizado"),
                        ],
                        default="",
                        max_length=15,
                        verbose_name="Estado anterior",
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("INGRESADO", "Ingresado"),
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("REALIZADO", "Realizado"),
                        ],
                        max_length=15,
                        verbose_name="Estado nuevo",
                    ),
                ),
                ("observacion", models.TextField(verbose_name="Observación")),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de compromiso",
                "verbose_name_plural": "Historial de compromisos",
                "db_table": "historial_compromiso",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Validacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APROBAR", "Aprobar"),
                            ("CORREGIR", "Corregir"),
                            ("RECHAZAR", "Rechazar"),
                        ],
                        max_length=10,
                        verbose_name="Decisión",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(
                        blank=True, default="", verbose_name="Observación"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "evidencia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validacion",
                        to="ActividadesApp.evidencia",
                        verbose_name="Evidencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validación",
                "verbose_name_plural": "Validaciones",
                "db_table": "validacion",
                "ordering": ["-fecha"],
            },
        ),
    ]
