# Generated by Django 4.2.30 on 2026-09-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ActividadesApp", "0001_initial"),
        ("UsuarioApp", "0001_initial"),
        ("IndicadoresApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="validacion",
            name="verificador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="validaciones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verificador",
            ),
        ),
        migrations.AddField(
            model_name="historialcompromiso",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="historial_compromisos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AddField(
            model_name="historialcompromiso",
            name="compromiso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to="ActividadesApp.compromiso",
                verbose_name="Compromiso",
            ),
        ),
        migrations.AddField(
            model_name="gestionsocial",
            name="atencion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gestiones",
                to="ActividadesApp.atencionsocial",
                verbose_name="Atención",
            ),
        ),
        migrations.AddField(
            model_name="evidencia",
            name="actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidencias",
                to="ActividadesApp.actividad",
                verbose_name="Actividad",
            ),
        ),
        migrations.AddField(
            model_name="evidencia",
            name="reemplaza_a",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reemplazada_por",
                to="ActividadesApp.evidencia",
                verbose_name="Reemplaza a",
            ),
        ),
        migrations.AddField(
            model_name="compromiso",
            name="delegacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compromisos",
                to="UsuarioApp.delegacion",
                verbose_name="Delegación",
            ),
        ),
        migrations.AddField(
            model_name="compromiso",
            name="registrado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compromisos_registrados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="compromiso",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compromisos_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="atencionsocial",
            name="actividad",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atencion_social",
                to="ActividadesApp.actividad",
                verbose_name="Actividad",
            ),
        ),
        migrations.AddField(
            model_name="atencionsocial",
            name="subtipo_atencion",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo": "SUBTIPO_ATENCION"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atenciones_subtipo",
                to="UsuarioApp.catalogo",
                verbose_name="Subtipo de atención",
            ),
        ),
        migrations.AddField(
            model_name="atencionsocial",
            name="tipo_atencion",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "TIPO_ATENCION"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atenciones_tipo",
                to="UsuarioApp.catalogo",
                verbose_name="Tipo de atención",
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="compromiso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actividades",
                to="ActividadesApp.compromiso",
                verbose_name="Compromiso (tubo)",
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="item",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "ITEM_GESTION"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actividades_item",
                to="UsuarioApp.catalogo",
                verbose_name="Ítem de gestión",
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actividades",
                to="IndicadoresApp.periodo",
                verbose_name="Periodo",
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo": "SERVICIO"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actividades_servicio",
                to="UsuarioApp.catalogo",
                verbose_name="Servicio",
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actividades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Funcionario",
            ),
        ),
    ]
