# Generated by Django 4.2.30 on 2026-09-25 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("CREACION", "Creación"),
                            ("MODIFICACION", "Modificación"),
                            ("ELIMINACION", "Eliminación"),
                            ("ACCESO_DENEGADO", "Acceso denegado"),
                        ],
                        max_length=15,
                        verbose_name="Evento",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                ("entidad", models.CharField(max_length=100, verbose_name="Entidad")),
                (
                    "id_entidad",
                    models.CharField(max_length=50, verbose_name="ID de la entidad"),
                ),
                (
                    "valor_anterior",
                    models.TextField(
                        blank=True, default="", verbose_name="Valor anterior"
                    ),
                ),
                (
                    "valor_nuevo",
                    models.TextField(
                        blank=True, default="", verbose_name="Valor nuevo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría",
                "verbose_name_plural": "Auditorías",
                "db_table": "auditoria",
                "ordering": ["-fecha"],
            },
        ),
    ]
