# Generated by Django 4.2.30 on 2026-09-25 16:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre del cargo"),
                ),
                (
                    "vigencia_inicio",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Vigencia desde"
                    ),
                ),
                (
                    "vigencia_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigencia hasta"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "db_table": "cargo",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Delegacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("RURAL", "Rural"),
                            ("LAS_COMPANIAS", "Las Compañías"),
                            ("LA_PAMPA", "La Pampa"),
                            ("LA_ANTENA", "La Antena"),
                            ("CENTRO", "Centro"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "ambito",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Ámbito"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delegación",
                "verbose_name_plural": "Delegaciones",
                "db_table": "delegacion",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("Admin", "Administrador"),
                            ("Coordinador", "Coordinador"),
                            ("Delegado", "Delegado"),
                            ("Verificador", "Verificador"),
                            ("Funcionario", "Funcionario"),
                            ("Consulta", "Usuario Consulta"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nombre", models.CharField(max_length=60, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Descripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "rol",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_column="rut",
                        error_messages={"unique": "Ya existe un usuario con ese RUT."},
                        max_length=12,
                        unique=True,
                        verbose_name="RUT",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        db_column="nombre",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        db_column="apellido",
                        max_length=100,
                        verbose_name="Apellido",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="activo", default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        db_column="creado",
                        default=django.utils.timezone.now,
                        verbose_name="Creado",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="UsuarioApp.cargo",
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "delegacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="UsuarioApp.delegacion",
                        verbose_name="Delegación",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuario",
                "ordering": ["first_name", "last_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de asignación",
                    ),
                ),
                (
                    "asignado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_que_asigno",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones",
                        to="UsuarioApp.rol",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol de usuario",
                "verbose_name_plural": "Roles de usuario",
                "db_table": "usuario_rol",
            },
        ),
        migrations.CreateModel(
            name="CodigoOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposito",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de sesión"),
                            ("RECUPERACION", "Recuperación de contraseña"),
                        ],
                        max_length=15,
                        verbose_name="Propósito",
                    ),
                ),
                ("codigo", models.CharField(max_length=6, verbose_name="Código")),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creado"
                    ),
                ),
                ("expira", models.DateTimeField(verbose_name="Expira")),
                ("usado", models.BooleanField(default=False, verbose_name="Usado")),
                (
                    "intentos",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Intentos"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_otp",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código OTP",
                "verbose_name_plural": "Códigos OTP",
                "db_table": "codigo_otp",
            },
        ),
        migrations.CreateModel(
            name="Catalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AREA", "Área"),
                            ("ITEM_GESTION", "Ítem de gestión"),
                            ("SERVICIO", "Servicio"),
                            ("TIPO_ATENCION", "Tipo de atención"),
                            ("SUBTIPO_ATENCION", "Subtipo de atención"),
                            ("TIPO_AJUSTE", "Tipo de ajuste"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opciones_del_area",
                        to="UsuarioApp.catalogo",
                        verbose_name="Área (vacío = todas)",
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hijos",
                        to="UsuarioApp.catalogo",
                        verbose_name="Catálogo padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catálogo",
                "verbose_name_plural": "Catálogos",
                "db_table": "catalogo",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="cargo",
            name="area",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo": "AREA"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cargos",
                to="UsuarioApp.catalogo",
                verbose_name="Área",
            ),
        ),
    ]
