# Generated by Django 4.2.30 on 2026-09-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodigoOTP',
        ),
    ]
