# Generated by Django 4.2.30 on 2026-09-25 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AjusteDesempeno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Valor (pp)"
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo")),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de desempeño",
                "verbose_name_plural": "Ajustes de desempeño",
                "db_table": "ajuste_desempeno",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="IndicadorDesempeno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_calculo",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Fecha de cálculo",
                    ),
                ),
                (
                    "avance_actual",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Avance actual"
                    ),
                ),
                (
                    "meta_esperada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Meta esperada",
                    ),
                ),
                (
                    "cumplimiento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="Cumplimiento (%)",
                    ),
                ),
                (
                    "cumplimiento_ponderado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Cumplimiento ponderado (%)",
                    ),
                ),
                (
                    "ajuste",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Ajuste (pp)",
                    ),
                ),
                (
                    "semaforo",
                    models.CharField(
                        choices=[
                            ("VERDE", "Verde"),
                            ("AMBAR", "Ámbar"),
                            ("ROJO", "Rojo"),
                        ],
                        default="ROJO",
                        max_length=5,
                        verbose_name="Semáforo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador de desempeño",
                "verbose_name_plural": "Indicadores de desempeño",
                "db_table": "indicador_desempeno",
                "ordering": ["-fecha_calculo"],
            },
        ),
        migrations.CreateModel(
            name="MetaDesempeno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_objetivo",
                    models.PositiveIntegerField(verbose_name="Meta del trimestre"),
                ),
                (
                    "unidad",
                    models.CharField(
                        default="actividades", max_length=50, verbose_name="Unidad"
                    ),
                ),
                (
                    "ponderador",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Ponderador (%)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta de desempeño",
                "verbose_name_plural": "Metas de desempeño",
                "db_table": "meta_desempeno",
                "ordering": ["cargo__nombre", "item__id"],
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_termino", models.DateField(verbose_name="Fecha de término")),
                (
                    "dias_computables",
                    models.PositiveIntegerField(verbose_name="Días computables"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("CERRADO", "Cerrado")],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "umbral_verde",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="Umbral verde (%)",
                    ),
                ),
                (
                    "umbral_ambar",
                    models.DecimalField(
                        decimal_places=2,
                        default=60,
                        max_digits=5,
                        verbose_name="Umbral ámbar (%)",
                    ),
                ),
                (
                    "umbral_colectivo",
                    models.DecimalField(
                        decimal_places=2,
                        default=80,
                        max_digits=5,
                        verbose_name="Umbral colectivo (%)",
                    ),
                ),
                (
                    "tope_cumplimiento",
                    models.DecimalField(
                        decimal_places=2,
                        default=150,
                        max_digits=5,
                        verbose_name="Tope de cumplimiento (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo",
                "verbose_name_plural": "Periodos",
                "db_table": "periodo",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
