# Generated by Django 4.2.30 on 2026-09-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("UsuarioApp", "0001_initial"),
        ("IndicadoresApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="metadesempeno",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metas",
                to="UsuarioApp.cargo",
                verbose_name="Cargo",
            ),
        ),
        migrations.AddField(
            model_name="metadesempeno",
            name="item",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "ITEM_GESTION"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metas",
                to="UsuarioApp.catalogo",
                verbose_name="Ítem de gestión",
            ),
        ),
        migrations.AddField(
            model_name="metadesempeno",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metas",
                to="IndicadoresApp.periodo",
                verbose_name="Periodo",
            ),
        ),
        migrations.AddField(
            model_name="indicadordesempeno",
            name="meta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicadores",
                to="IndicadoresApp.metadesempeno",
                verbose_name="Meta",
            ),
        ),
        migrations.AddField(
            model_name="indicadordesempeno",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicadores",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="ajustedesempeno",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ajustes",
                to="IndicadoresApp.periodo",
                verbose_name="Periodo",
            ),
        ),
        migrations.AddField(
            model_name="ajustedesempeno",
            name="registrado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ajustes_registrados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="ajustedesempeno",
            name="tipo",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "TIPO_AJUSTE"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ajustes",
                to="UsuarioApp.catalogo",
                verbose_name="Tipo de ajuste",
            ),
        ),
        migrations.AddField(
            model_name="ajustedesempeno",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ajustes_recibidos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario evaluado",
            ),
        ),
    ]
